/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.BadgeException;
import backend.BadgeStorage;
import backend.FullScoreBadge;
import backend.UserData;
import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

// Creator: TIONG WOEI CHIN (101224)
// Tester: CHIN PEI YI (98485)
// Badge Collection Panel
public class BadgePanel extends javax.swing.JPanel {
    
    private JPanel mainPanel;
    
    // Constructor
    public BadgePanel() {
        initComponents();
        defaultCollection();
        updateBadgeCollection();
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
    
    // Empty badge collection
    private void defaultCollection() {
        badge1_name.setText("The DeepFake Primer");
        badge2_name.setText("Spot the Fake");
        badge3_name.setText("Consequences of Unreal");
        badge4_name.setText("Fake Fixer");
        badge1_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 1 -<br>Deepfake Definition</div></html>");
        badge2_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 2 -<br>Deepfake Detection</div></html>");
        badge3_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 3 -<br>Effects of Deepfake</div></html>");
        badge4_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 4 -<br>Solutions and Prevention</div></html>");
        ImageIcon icon = new ImageIcon(getClass().getResource("/Images/badge0.png"));
        badge1_icon.setIcon(icon);
        badge2_icon.setIcon(icon);
        badge3_icon.setIcon(icon);
        badge4_icon.setIcon(icon);
    }
    
    // Update badge collection
    private void updateBadgeCollection() {
        String currentUser = UserData.getUsername();
        System.out.println("Update Badge collection...");
        System.out.println("Current user: " + currentUser);
        
        List<String> earned = new ArrayList<>();
        
        try {
            // Load earned badges list
            earned = BadgeStorage.loadBadges(currentUser);
            System.out.println("Earned badges: " + earned);
        } catch (BadgeException e) {
            JOptionPane.showMessageDialog(this, 
                "An error occurred for loading badges:\n" + e.getMessage(),
                "Badge Load Error", 
                JOptionPane.ERROR_MESSAGE);
        }
      
        // Loop through all 4 badge topics
        for (int i = 1; i <= 4; i++) { // Topic 1 to 4
            String topic = String.valueOf(i);
            FullScoreBadge badge = FullScoreBadge.getBadgeForTopic(topic);
          
            // Determine icon path based on whether badge is earned
            String iconPath;
            if (earned.contains(badge.getBadgeName())) {
                iconPath = "/Images/badge" + i + ".png"; // earned badge
            } else {
                iconPath = "/Images/badge0.png"; // locked badge
            }

            ImageIcon icon = new ImageIcon(getClass().getResource(iconPath));

            // Set icon to correct label
            switch (i) {
                case 1 -> badge1_icon.setIcon(icon);
                case 2 -> badge2_icon.setIcon(icon);
                case 3 -> badge3_icon.setIcon(icon);
                case 4 -> badge4_icon.setIcon(icon);
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        badgeTitleLabel = new javax.swing.JLabel();
        backMenuButton = new javax.swing.JButton();
        badge3_icon = new javax.swing.JLabel();
        badge3_name = new javax.swing.JLabel();
        badge1_icon = new javax.swing.JLabel();
        badge1_name = new javax.swing.JLabel();
        badge1_desc = new javax.swing.JLabel();
        badge2_icon = new javax.swing.JLabel();
        badge2_name = new javax.swing.JLabel();
        badge3_desc = new javax.swing.JLabel();
        badge4_icon = new javax.swing.JLabel();
        badge4_name = new javax.swing.JLabel();
        badge4_desc = new javax.swing.JLabel();
        badge2_desc = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(430, 670));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        badgeTitleLabel.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        badgeTitleLabel.setForeground(new java.awt.Color(255, 255, 204));
        badgeTitleLabel.setText("Collect your badges!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 5, 0);
        add(badgeTitleLabel, gridBagConstraints);

        backMenuButton.setBackground(new java.awt.Color(51, 0, 51));
        backMenuButton.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        backMenuButton.setForeground(new java.awt.Color(255, 255, 204));
        backMenuButton.setText("<");
        backMenuButton.setBorder(null);
        backMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 10, 0, 25);
        add(backMenuButton, gridBagConstraints);

        badge3_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge3_icon.setText("badge1");
        badge3_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 10, 60);
        add(badge3_icon, gridBagConstraints);

        badge3_name.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        badge3_name.setForeground(new java.awt.Color(255, 255, 255));
        badge3_name.setText("Consequences of  Unreal");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 30);
        add(badge3_name, gridBagConstraints);

        badge1_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge1_icon.setText("badge1");
        badge1_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(50, 30, 10, 60);
        add(badge1_icon, gridBagConstraints);

        badge1_name.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        badge1_name.setForeground(new java.awt.Color(255, 255, 255));
        badge1_name.setText("The Deepfake Primer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 60);
        add(badge1_name, gridBagConstraints);

        badge1_desc.setFont(new java.awt.Font("BatangChe", 0, 12)); // NOI18N
        badge1_desc.setForeground(new java.awt.Color(255, 255, 255));
        badge1_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge1_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 1 -<br>Deepfake Definition</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        add(badge1_desc, gridBagConstraints);

        badge2_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge2_icon.setText("badge1");
        badge2_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 10, 50);
        add(badge2_icon, gridBagConstraints);

        badge2_name.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        badge2_name.setForeground(new java.awt.Color(255, 255, 255));
        badge2_name.setText("Spot the Fake");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 44);
        add(badge2_name, gridBagConstraints);

        badge3_desc.setFont(new java.awt.Font("BatangChe", 0, 12)); // NOI18N
        badge3_desc.setForeground(new java.awt.Color(255, 255, 255));
        badge3_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge3_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 3 -<br>Effects of Deepfake</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 70, 0);
        add(badge3_desc, gridBagConstraints);

        badge4_icon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge4_icon.setText("badge1");
        badge4_icon.setPreferredSize(new java.awt.Dimension(80, 80));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 10, 50);
        add(badge4_icon, gridBagConstraints);

        badge4_name.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        badge4_name.setForeground(new java.awt.Color(255, 255, 255));
        badge4_name.setText("Fake Fixer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 58);
        add(badge4_name, gridBagConstraints);

        badge4_desc.setFont(new java.awt.Font("BatangChe", 0, 12)); // NOI18N
        badge4_desc.setForeground(new java.awt.Color(255, 255, 255));
        badge4_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge4_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 4 -<br>Solutions and Prevention</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 70, 14);
        add(badge4_desc, gridBagConstraints);

        badge2_desc.setFont(new java.awt.Font("BatangChe", 0, 12)); // NOI18N
        badge2_desc.setForeground(new java.awt.Color(255, 255, 255));
        badge2_desc.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        badge2_desc.setText("<html><div style='text-align: center;'>Scored full marks for<br>quiz Topic 2 -<br>Deepfake Detection</div></html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 15);
        add(badge2_desc, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuButtonActionPerformed
        // Switch to MenuPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "menu");
    }//GEN-LAST:event_backMenuButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backMenuButton;
    private javax.swing.JLabel badge1_desc;
    private javax.swing.JLabel badge1_icon;
    private javax.swing.JLabel badge1_name;
    private javax.swing.JLabel badge2_desc;
    private javax.swing.JLabel badge2_icon;
    private javax.swing.JLabel badge2_name;
    private javax.swing.JLabel badge3_desc;
    private javax.swing.JLabel badge3_icon;
    private javax.swing.JLabel badge3_name;
    private javax.swing.JLabel badge4_desc;
    private javax.swing.JLabel badge4_icon;
    private javax.swing.JLabel badge4_name;
    private javax.swing.JLabel badgeTitleLabel;
    // End of variables declaration//GEN-END:variables
}
