/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.Question;
import backend.Quiz1;
import backend.QuizException;
import backend.ResultException;

import backend.ResultLog;
import backend.TimerException;
import backend.TimerManager;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

// Creator: HII SIEW CHIENG (97444)
// Tester: CHAN CHIN XUAN (98439)

// Fill in blanks Quiz for Topic 1 - DeepFake Definition
public class FillBlanksPanel extends javax.swing.JPanel implements IQuizPanel{
    
    private String username;
    private long timeTaken;
    private JPanel mainPanel;
    private ResultPanel resultPanel;
    private FillBlanksPanel fbPanel;
    private Quiz1 quiz1;
    private TimerManager timer1;
    private int currentIdx = 0;
    private String blanksAns = "";
    
    // Constructor
    public FillBlanksPanel() {
        initComponents();
        
        try {
            quiz1 = new Quiz1();
        } catch (QuizException e) {
            JOptionPane.showMessageDialog(null, "Error loading quiz: " + e.getMessage(), "Quiz Load Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            timer1 = new TimerManager(this::updateTimerLabel);  // may throw TimerException
        } catch (TimerException e) {
            JOptionPane.showMessageDialog(null, "Error initializing timer: " + e.getMessage(), "Timer Init Error", JOptionPane.ERROR_MESSAGE);
        }   
    }
    
    public void initializeQuiz() {
        if (quiz1 != null) {
            displayQuestion();
        }
    }
    
    
    public void setUsername(String username) {
        this.username = username;
    }
    
    public void setTimeTaken(long seconds) {
        this.timeTaken = seconds;
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
    
    public void setResultPanel(ResultPanel resultPanel) {
        this.resultPanel = resultPanel;
    }
    
    //== Overriden methods from IQuizPanel ===
    @Override
    public void displayQuestion() {
        // If quiz completed
        if (currentIdx >= quiz1.getQuestion().size()) {
                return;
        }
        
        // Assign each question to Question class instance
        Question q = quiz1.getQuestion().get(currentIdx);
        
        // Get topic
        topicLabel.setText("Quiz " + quiz1.getTopic());
        // Get score
        scoreLabel.setText("Score " + quiz1.getScore());
        // Get question
        questionTextArea.setText(q.getQuestionText());
        questionNoLabel.setText("Question " + (currentIdx+1) + " / " + quiz1.getQuestion().size());
        
    }   
    
    @Override
    public void updateTimerLabel(long seconds) {
        timerLabel.setText("Time " + seconds + "s");
    }
    
    @Override
    public void startTimer() {
        try {
            if (timer1 != null) {
                timer1.startTimer();  // can throw TimerException if already running
            }
        } catch (TimerException ex) {
            JOptionPane.showMessageDialog(null, "Error starting timer: " + ex.getMessage(), "Timer Start Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public void stopTimer() {
        timer1.stopTimer();
    }
    
    @Override
    public void resetQuiz() {
        currentIdx = 0;
        blanksAns = "";
        ansField.setText("");
        quiz1.setScore(0);
        updateTimerLabel(0);
        
        try {
            // Restart if needed
            startTimer();
            this.quiz1 = new Quiz1();
            // Re-display first question
            displayQuestion();

            revalidate();
            repaint();
            //startTimer();
        } catch (QuizException e) {
            JOptionPane.showMessageDialog(this, "Failed to reset quiz: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        questionNoLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        backQuizButton1 = new javax.swing.JButton();
        topicLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        timerIcon = new javax.swing.JLabel();
        scoreIcon = new javax.swing.JLabel();
        nextQuestionBtn = new javax.swing.JButton();
        instructionLabel = new javax.swing.JLabel();
        ansTextLabel = new javax.swing.JLabel();
        ansField = new javax.swing.JTextField();
        questionTextArea = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(51, 0, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(2000, 600));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        questionNoLabel.setBackground(new java.awt.Color(255, 255, 204));
        questionNoLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        questionNoLabel.setForeground(new java.awt.Color(51, 0, 51));
        questionNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionNoLabel.setText("Question 1/10");
        questionNoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        questionNoLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(30, 128, 0, 0);
        jPanel1.add(questionNoLabel, gridBagConstraints);

        topPanel.setBackground(new java.awt.Color(51, 0, 51));
        topPanel.setLayout(new java.awt.GridBagLayout());

        backQuizButton1.setBackground(new java.awt.Color(51, 0, 51));
        backQuizButton1.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        backQuizButton1.setForeground(new java.awt.Color(255, 255, 255));
        backQuizButton1.setText("<");
        backQuizButton1.setBorder(null);
        backQuizButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQuizButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 330);
        topPanel.add(backQuizButton1, gridBagConstraints);

        topicLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(255, 255, 204));
        topicLabel.setText("Topic 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        topPanel.add(topicLabel, gridBagConstraints);

        timerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(255, 255, 204));
        timerLabel.setText("Time 10s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 35);
        topPanel.add(timerLabel, gridBagConstraints);

        scoreLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 204));
        scoreLabel.setText("Score  20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        topPanel.add(scoreLabel, gridBagConstraints);

        timerIcon.setBackground(new java.awt.Color(51, 0, 51));
        timerIcon.setForeground(new java.awt.Color(255, 255, 255));
        timerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timer.png"))); // NOI18N
        timerIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        timerIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        topPanel.add(timerIcon, gridBagConstraints);

        scoreIcon.setBackground(new java.awt.Color(51, 0, 51));
        scoreIcon.setForeground(new java.awt.Color(255, 255, 255));
        scoreIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.png"))); // NOI18N
        scoreIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        topPanel.add(scoreIcon, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.1;
        jPanel1.add(topPanel, gridBagConstraints);

        nextQuestionBtn.setBackground(new java.awt.Color(255, 255, 204));
        nextQuestionBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nextQuestionBtn.setForeground(new java.awt.Color(51, 0, 51));
        nextQuestionBtn.setText("Next");
        nextQuestionBtn.setMinimumSize(new java.awt.Dimension(50, 20));
        nextQuestionBtn.setOpaque(true);
        nextQuestionBtn.setPreferredSize(new java.awt.Dimension(50, 20));
        nextQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(45, 152, 100, 0);
        jPanel1.add(nextQuestionBtn, gridBagConstraints);

        instructionLabel.setBackground(new java.awt.Color(51, 0, 51));
        instructionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        instructionLabel.setForeground(new java.awt.Color(255, 255, 204));
        instructionLabel.setText("Please fill in the blanks for each question.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 25, 0);
        jPanel1.add(instructionLabel, gridBagConstraints);

        ansTextLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ansTextLabel.setForeground(new java.awt.Color(255, 255, 255));
        ansTextLabel.setText("Answer: ");
        ansTextLabel.setToolTipText("");
        ansTextLabel.setMinimumSize(new java.awt.Dimension(59, 16));
        ansTextLabel.setPreferredSize(new java.awt.Dimension(59, 16));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 10, 0);
        jPanel1.add(ansTextLabel, gridBagConstraints);

        ansField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ansField.setForeground(new java.awt.Color(51, 0, 51));
        ansField.setMinimumSize(new java.awt.Dimension(150, 20));
        ansField.setPreferredSize(new java.awt.Dimension(150, 20));
        ansField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 15, 0, 0);
        jPanel1.add(ansField, gridBagConstraints);

        questionTextArea.setEditable(false);
        questionTextArea.setBackground(new java.awt.Color(51, 0, 51));
        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        questionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(5);
        questionTextArea.setText("Deepfake technology is a type of __________ used to create fake but realistic images, videos, and audio recordings.");
        questionTextArea.setMinimumSize(new java.awt.Dimension(350, 100));
        questionTextArea.setPreferredSize(new java.awt.Dimension(350, 100));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 0, 0);
        jPanel1.add(questionTextArea, gridBagConstraints);

        add(jPanel1, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents

    private void backQuizButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQuizButton1ActionPerformed
        stopTimer();
        // Switch to QuizPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "quiz");
        resetQuiz();
        stopTimer();
    }//GEN-LAST:event_backQuizButton1ActionPerformed

    private void nextQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionBtnActionPerformed
       
        // Get user answer
        blanksAns = ansField.getText().trim();
       
        // Validate empty input
        if (blanksAns.isEmpty() || blanksAns.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Your answer cannot be empty.","Input error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Get question
        Question currentQuestion = quiz1.getQuestion().get(currentIdx);

        // Check answer
        System.out.println("fbquiz, check answer...");
        if (quiz1.checkAnswer(currentQuestion, blanksAns)) {
            System.out.println("Input answer is correct: " + blanksAns);
            JOptionPane.showMessageDialog(this, "Correct! +10");

        } else {
            System.out.println("Input answer is wrong: " + blanksAns);
            JOptionPane.showMessageDialog(this, "Wrong!");

        }
        
        ansField.setText("");
        // Display next question
        currentIdx++;

        if (currentIdx < quiz1.getQuestion().size()) {
            displayQuestion();
        } else {
            // Quiz completed
            // TImer stop
            stopTimer();
            setTimeTaken(timer1.getSeconds());
            // Result display
            // Switch to ResultPanel
            CardLayout card = (CardLayout) mainPanel.getLayout();
            card.show(mainPanel, "result");
            
            try {
                ResultLog.saveResult(1, quiz1.getScore(), timeTaken, quiz1.getCorrectCnt(), quiz1.getWrongCnt());
                resultPanel.displayResult(quiz1.getScore(), quiz1.getQuestion().size(), timeTaken, quiz1.getCorrectCnt(), quiz1.getWrongCnt(), quiz1.getTopic());
            } catch (ResultException e) {
                    JOptionPane.showMessageDialog(this, 
                        "An error occurred for saving result:\n" + e.getMessage(),
                        "Result Saving Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            
        }

    }//GEN-LAST:event_nextQuestionBtnActionPerformed

    private void ansFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ansField;
    private javax.swing.JLabel ansTextLabel;
    private javax.swing.JButton backQuizButton1;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nextQuestionBtn;
    private javax.swing.JLabel questionNoLabel;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JLabel scoreIcon;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel timerIcon;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables

    
}
