/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.UserData;
import backend.UserDataException;
import java.awt.*;
import javax.swing.*;

// Creator: CHIN PEI YI (98485)
// Tester: TIONG WOEI CHIN (101224)

// Login Panel
public class LoginPanel extends javax.swing.JPanel {

    private final char defaultEcho;
    private JPanel mainPanel;
    
    // Constructor
    public LoginPanel() {
        initComponents(); 
        defaultEcho = passwordField.getEchoChar();
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        loginLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        startButton = new javax.swing.JButton();
        signUpPageBtn = new javax.swing.JButton();
        eyeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 51));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        loginLabel.setFont(new java.awt.Font("Yu Gothic Medium", 1, 34)); // NOI18N
        loginLabel.setForeground(new java.awt.Color(255, 255, 204));
        loginLabel.setText("Login");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(32, 30, 32, 0);
        add(loginLabel, gridBagConstraints);

        usernameField.setBackground(new java.awt.Color(51, 0, 51));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        usernameField.setMinimumSize(new java.awt.Dimension(0, 0));
        usernameField.setOpaque(true);
        usernameField.setPreferredSize(new java.awt.Dimension(220, 50));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 18, 0);
        add(usernameField, gridBagConstraints);

        passwordField.setBackground(new java.awt.Color(51, 0, 51));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        passwordField.setMinimumSize(null);
        passwordField.setOpaque(true);
        passwordField.setPreferredSize(new java.awt.Dimension(220, 50));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 3, 0);
        add(passwordField, gridBagConstraints);

        startButton.setBackground(new java.awt.Color(255, 255, 204));
        startButton.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(51, 0, 51));
        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        startButton.setMinimumSize(new java.awt.Dimension(0, 0));
        startButton.setPreferredSize(new java.awt.Dimension(100, 35));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(35, 30, 0, 0);
        add(startButton, gridBagConstraints);

        signUpPageBtn.setBackground(new java.awt.Color(51, 0, 51));
        signUpPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        signUpPageBtn.setText("New here? Sign Up");
        signUpPageBtn.setBorder(null);
        signUpPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpPageBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 0, 0);
        add(signUpPageBtn, gridBagConstraints);

        eyeButton.setBackground(new java.awt.Color(51, 0, 51));
        eyeButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        eyeButton.setForeground(new java.awt.Color(255, 255, 255));
        eyeButton.setText("👁");
        eyeButton.setBorder(null);
        eyeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(13, 11, 0, 0);
        add(eyeButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_usernameFieldActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    
    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // Store username and password in csv file
        String inputUsername;
        String inputPassword;

        // Get input string
        inputUsername = usernameField.getText().trim();
        inputPassword = new String(passwordField.getPassword()).trim();
        
        // DEBUG
        System.out.println("===LOGIN===");
        System.out.println("Input username: " + inputUsername);
        System.out.println("Input password: " + inputPassword);
        
        // Validate empty input
        if (inputUsername.isEmpty() || inputPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty.","Input error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Validate user credentials
        if (UserData.validateCredentials(inputUsername, inputPassword)) {
            // Store username for later use
            UserData.setUsername(inputUsername);
            UserData.setPassword(inputPassword);
           
            // Show welcome message if account existed
            JOptionPane.showMessageDialog(this, "Welcome back, " + inputUsername + "!");
            
            MenuPanel menuPanel = new MenuPanel();
            menuPanel.setMainPanel(mainPanel);  
            mainPanel.add(menuPanel, "menu");   
            // Switch to MenuPanel
            CardLayout card = (CardLayout)(mainPanel.getLayout());
            card.show(mainPanel,"menu");
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect username or password. Please try again or sign up first.", "Account not found", JOptionPane.ERROR_MESSAGE);
            }
        } catch (UserDataException e) {
            JOptionPane.showMessageDialog(this, 
                "An error occurred while validating credentials:\n" + e.getMessage(),
                "Validation Error", 
                JOptionPane.ERROR_MESSAGE);
        }
  
        usernameField.setText("");
        passwordField.setText("");
        
    }//GEN-LAST:event_startButtonActionPerformed

    private void signUpPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpPageBtnActionPerformed
        usernameField.setText("");
        passwordField.setText("");
        // Switch to SignUpPanel
        CardLayout card = (CardLayout)(mainPanel.getLayout());
        card.show(mainPanel,"signUp");
    }//GEN-LAST:event_signUpPageBtnActionPerformed

    
    
    private void eyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeButtonActionPerformed
        eyeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        if (passwordField.getEchoChar() == 0) {
            passwordField.setEchoChar(defaultEcho); // Restore original mask
        } else {
            passwordField.setEchoChar((char) 0); // Show password
        }
    }//GEN-LAST:event_eyeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eyeButton;
    private javax.swing.JLabel loginLabel;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton signUpPageBtn;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
