/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.Question;
import backend.Quiz4;
import backend.QuizException;
import backend.ResultException;
import backend.ResultLog;
import backend.TimerException;
import backend.TimerManager;
import java.awt.*;
import javax.swing.*;

// Creator: HII SIEW CHIENG (97444)
// Tester: CHAN CHIN XUAN (98439)

// Fill in blanks Quiz for Topic 4 - Solution and Prevention
public class MCQPanel extends javax.swing.JPanel implements IQuizPanel{
    
    private String username;
    private MCQPanel mcqPanel;
    private ResultPanel resultPanel;
    private Quiz4 quiz4;
    private TimerManager timer4;
    private int currentIdx = 0;
    private String selected = "";
    private JPanel mainPanel;
    private long timeTaken;
    
    // Constructor
    public MCQPanel() {
        initComponents();
        
        try {
            quiz4 = new Quiz4();
        } catch (QuizException e) {
            JOptionPane.showMessageDialog(null, "Error loading quiz: " + e.getMessage(), "Quiz Load Error", JOptionPane.ERROR_MESSAGE);
        }
        
        try {
            timer4 = new TimerManager(this::updateTimerLabel);
        } catch (TimerException e) {
            JOptionPane.showMessageDialog(null, "Error initializing timer: " + e.getMessage(), "Timer Init Error", JOptionPane.ERROR_MESSAGE);
        }   
        
        // Group radioButton to allow single selection
        buttonGroup1.add(opt1);
        buttonGroup1.add(opt2);
        buttonGroup1.add(opt3);
        buttonGroup1.add(opt4);
    }
    
    public void initializeQuiz() {
        if (quiz4 != null) {
            displayQuestion();
        }
    }
  
    public void setUsername(String username) {
        this.username = username;
    }
    
    public void setTimeTaken(long seconds) {
        this.timeTaken = seconds;
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
    
    public void setResultPanel(ResultPanel resultPanel) {
        this.resultPanel = resultPanel;
    }
    
    //== Overriden methods from IQuizPanel ===
    @Override
    public void displayQuestion() {
        // If quiz completed
        if (currentIdx >= quiz4.getQuestion().size()) {
                return;
        }
        
        // Assign each question to Question class instance
        Question q = quiz4.getQuestion().get(currentIdx);
        
        // Get topic
        topicLabel.setText("Quiz " + quiz4.getTopic());
        
        // Get score
        scoreLabel.setText("Score " + quiz4.getScore());
        // Get question
        questionTextArea.setText(q.getQuestionText());
        questionNoLabel.setText("Question " + (currentIdx+1) + " / " + quiz4.getQuestion().size());
        // Get choices
        java.util.List<String> choices = q.getChoices();
        opt1.setText(choices.get(0));
        opt2.setText(choices.get(1));
        opt3.setText(choices.get(2));
        opt4.setText(choices.get(3));
    }   
    
    @Override
    public void updateTimerLabel(long seconds) {
        timerLabel.setText("Time " + seconds + "s");
    }
    
    @Override
    public void startTimer() {
        try {
            if (timer4 != null) {
                timer4.startTimer();  // can throw TimerException if already running
            }
        } catch (TimerException ex) {
            JOptionPane.showMessageDialog(null, "Error starting timer: " + ex.getMessage(), "Timer Start Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    @Override
    public void stopTimer() {
        timer4.stopTimer();
    }
    
    @Override
    public void resetQuiz() {
        System.out.println("MCQ Panel, Quiz resetting!");
        currentIdx = 0;
        selected = "";
        quiz4.setScore(0);
        updateTimerLabel(0);
        
        try {
            startTimer();
            // Restart if needed
            this.quiz4 = new Quiz4();
            // Clear previous selection
            buttonGroup1.clearSelection();
            // Re-display first question
            displayQuestion();

            revalidate();
            repaint();
            //startTimer();
        } catch (QuizException e) {
            JOptionPane.showMessageDialog(this, "Failed to reset quiz: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        opt1 = new javax.swing.JRadioButton();
        opt2 = new javax.swing.JRadioButton();
        opt3 = new javax.swing.JRadioButton();
        opt4 = new javax.swing.JRadioButton();
        instructionLabel = new javax.swing.JLabel();
        topPanel = new javax.swing.JPanel();
        backQuizButton1 = new javax.swing.JButton();
        topicLabel = new javax.swing.JLabel();
        timerLabel = new javax.swing.JLabel();
        scoreLabel = new javax.swing.JLabel();
        timerIcon = new javax.swing.JLabel();
        scoreIcon = new javax.swing.JLabel();
        questionNoLabel = new javax.swing.JLabel();
        questionTextArea = new javax.swing.JTextArea();
        nextQuestionBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(430, 670));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        opt1.setBackground(new java.awt.Color(51, 0, 51));
        opt1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opt1.setForeground(new java.awt.Color(255, 255, 255));
        opt1.setMargin(new java.awt.Insets(10, 0, 20, 10));
        opt1.setMaximumSize(new java.awt.Dimension(26, 30));
        opt1.setMinimumSize(new java.awt.Dimension(26, 30));
        opt1.setPreferredSize(new java.awt.Dimension(26, 30));
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(15, 20, 0, 0);
        add(opt1, gridBagConstraints);

        opt2.setBackground(new java.awt.Color(51, 0, 51));
        opt2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opt2.setForeground(new java.awt.Color(255, 255, 255));
        opt2.setMargin(new java.awt.Insets(10, 0, 20, 10));
        opt2.setPreferredSize(new java.awt.Dimension(1000, 45));
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        add(opt2, gridBagConstraints);

        opt3.setBackground(new java.awt.Color(51, 0, 51));
        opt3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opt3.setForeground(new java.awt.Color(255, 255, 255));
        opt3.setContentAreaFilled(false);
        opt3.setMargin(new java.awt.Insets(10, 0, 20, 10));
        opt3.setPreferredSize(new java.awt.Dimension(1000, 45));
        opt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        add(opt3, gridBagConstraints);

        opt4.setBackground(new java.awt.Color(51, 0, 51));
        opt4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        opt4.setForeground(new java.awt.Color(255, 255, 255));
        opt4.setMargin(new java.awt.Insets(10, 0, 20, 10));
        opt4.setPreferredSize(new java.awt.Dimension(1000, 45));
        opt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        add(opt4, gridBagConstraints);

        instructionLabel.setBackground(new java.awt.Color(51, 0, 51));
        instructionLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        instructionLabel.setForeground(new java.awt.Color(255, 255, 204));
        instructionLabel.setText("Please choose ONE(1) option for each question.");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(30, 0, 20, 0);
        add(instructionLabel, gridBagConstraints);

        topPanel.setBackground(new java.awt.Color(51, 0, 51));
        topPanel.setLayout(new java.awt.GridBagLayout());

        backQuizButton1.setBackground(new java.awt.Color(51, 0, 51));
        backQuizButton1.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        backQuizButton1.setForeground(new java.awt.Color(255, 255, 255));
        backQuizButton1.setText("<");
        backQuizButton1.setBorder(null);
        backQuizButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backQuizButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 25, 330);
        topPanel.add(backQuizButton1, gridBagConstraints);

        topicLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        topicLabel.setForeground(new java.awt.Color(255, 255, 204));
        topicLabel.setText("Topic 1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        topPanel.add(topicLabel, gridBagConstraints);

        timerLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        timerLabel.setForeground(new java.awt.Color(255, 255, 204));
        timerLabel.setText("Time 10s");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 35);
        topPanel.add(timerLabel, gridBagConstraints);

        scoreLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 18)); // NOI18N
        scoreLabel.setForeground(new java.awt.Color(255, 255, 204));
        scoreLabel.setText("Score  20");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        topPanel.add(scoreLabel, gridBagConstraints);

        timerIcon.setBackground(new java.awt.Color(51, 0, 51));
        timerIcon.setForeground(new java.awt.Color(255, 255, 255));
        timerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/timer.png"))); // NOI18N
        timerIcon.setMaximumSize(new java.awt.Dimension(50, 50));
        timerIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        topPanel.add(timerIcon, gridBagConstraints);

        scoreIcon.setBackground(new java.awt.Color(51, 0, 51));
        scoreIcon.setForeground(new java.awt.Color(255, 255, 255));
        scoreIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/star.png"))); // NOI18N
        scoreIcon.setPreferredSize(new java.awt.Dimension(50, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        topPanel.add(scoreIcon, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.1;
        add(topPanel, gridBagConstraints);

        questionNoLabel.setBackground(new java.awt.Color(255, 255, 204));
        questionNoLabel.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        questionNoLabel.setForeground(new java.awt.Color(51, 0, 51));
        questionNoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        questionNoLabel.setText("Question 1/10");
        questionNoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        questionNoLabel.setOpaque(true);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 11;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(20, 145, 0, 0);
        add(questionNoLabel, gridBagConstraints);

        questionTextArea.setEditable(false);
        questionTextArea.setBackground(new java.awt.Color(51, 0, 51));
        questionTextArea.setColumns(20);
        questionTextArea.setFont(new java.awt.Font("MS UI Gothic", 1, 16)); // NOI18N
        questionTextArea.setForeground(new java.awt.Color(255, 255, 255));
        questionTextArea.setLineWrap(true);
        questionTextArea.setRows(5);
        questionTextArea.setText("Deepfake technology is a type of __________ used to create fake but realistic images, videos, and audio recordings.");
        questionTextArea.setMinimumSize(new java.awt.Dimension(350, 50));
        questionTextArea.setPreferredSize(new java.awt.Dimension(350, 50));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 0, 0);
        add(questionTextArea, gridBagConstraints);

        nextQuestionBtn.setBackground(new java.awt.Color(255, 255, 204));
        nextQuestionBtn.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N
        nextQuestionBtn.setForeground(new java.awt.Color(51, 0, 51));
        nextQuestionBtn.setText("Next");
        nextQuestionBtn.setMinimumSize(new java.awt.Dimension(50, 20));
        nextQuestionBtn.setOpaque(true);
        nextQuestionBtn.setPreferredSize(new java.awt.Dimension(50, 20));
        nextQuestionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextQuestionBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.ipadx = 16;
        gridBagConstraints.ipady = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(40, 174, 30, 0);
        add(nextQuestionBtn, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void opt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt4ActionPerformed

    private void opt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt3ActionPerformed

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1ActionPerformed

    private void backQuizButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backQuizButton1ActionPerformed
        stopTimer();
        // Switch to QuizPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "quiz");
        resetQuiz();
        stopTimer();
    }//GEN-LAST:event_backQuizButton1ActionPerformed

    private void nextQuestionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextQuestionBtnActionPerformed
        // Get selection
        if (opt1.isSelected()) selected = "A";
        else if (opt2.isSelected()) selected = "B";
        else if (opt3.isSelected()) selected = "C";
        else if (opt4.isSelected()) selected = "D";
        
        // If not answer selected
        if (selected.equals("")) {
            JOptionPane.showMessageDialog(this, "Please select an option!");
            return;
        } 
        // Get question
        Question currentQuestion = quiz4.getQuestion().get(currentIdx);
        
        // Check answer
        System.out.println("mcqquiz, check answer...");
        if (quiz4.checkAnswer(currentQuestion, selected)) {
            System.out.println("Option selected is correct: " + selected);
            JOptionPane.showMessageDialog(this, "Correct! +10");
            
        } else {
            System.out.println("Option selected is wrong: " + selected);
            JOptionPane.showMessageDialog(this, "Wrong!");
            
        }
        
        selected = "";
        buttonGroup1.clearSelection();
        // Display next question
        currentIdx++;
        
        if (currentIdx < quiz4.getQuestion().size()) {
            displayQuestion();
        } else {
            // Quiz completed
            System.out.println("MCQ Panel, Quiz end!");
            // TImer stop
            stopTimer();
            setTimeTaken(timer4.getSeconds());
           
            // Result display
            // Switch to ResultPanel
            CardLayout card = (CardLayout) mainPanel.getLayout();
            card.show(mainPanel, "result");
          //  JOptionPane.showMessageDialog(this,"Your score: "+ quiz4.getScore());
         //   JOptionPane.showMessageDialog(this, "Quiz Completed!");
            try {
                ResultLog.saveResult(4, quiz4.getScore(), timeTaken, quiz4.getCorrectCnt(), quiz4.getWrongCnt());
                resultPanel.displayResult(quiz4.getScore(), quiz4.getQuestion().size(), timeTaken, quiz4.getCorrectCnt(), quiz4.getWrongCnt(), quiz4.getTopic());
            } catch (ResultException e) {
                    JOptionPane.showMessageDialog(this, 
                        "An error occurred for saving result:\n" + e.getMessage(),
                        "Result Saving Error", 
                        JOptionPane.ERROR_MESSAGE);
                }
            
        }
    }//GEN-LAST:event_nextQuestionBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backQuizButton1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel instructionLabel;
    private javax.swing.JButton nextQuestionBtn;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    private javax.swing.JRadioButton opt3;
    private javax.swing.JRadioButton opt4;
    private javax.swing.JLabel questionNoLabel;
    private javax.swing.JTextArea questionTextArea;
    private javax.swing.JLabel scoreIcon;
    private javax.swing.JLabel scoreLabel;
    private javax.swing.JLabel timerIcon;
    private javax.swing.JLabel timerLabel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JLabel topicLabel;
    // End of variables declaration//GEN-END:variables
}
