/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.UserData;
import java.awt.CardLayout;
import javax.swing.*;

// Creator: TIONG WOEI CHIN (101224)
// Tester: CHIN PEI YI (98485)

// Main Menu Panel
public class MenuPanel extends javax.swing.JPanel {
    
    private JPanel mainPanel;
    
    // Constructor
    public MenuPanel() {
        initComponents();
        this.userLabel.setText("Welcome, " + UserData.getUsername());
    }
  
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mainMenu = new javax.swing.JPanel();
        menuTextLabel = new javax.swing.JLabel();
        learningButton = new javax.swing.JButton();
        quizButton = new javax.swing.JButton();
        badgeButton = new javax.swing.JButton();
        leaderboardButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        switchAccBtn = new javax.swing.JButton();
        userLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 0, 51));
        setLayout(new java.awt.GridBagLayout());

        mainMenu.setBackground(new java.awt.Color(51, 0, 51));
        mainMenu.setPreferredSize(new java.awt.Dimension(300, 500));
        mainMenu.setLayout(new java.awt.GridBagLayout());

        menuTextLabel.setFont(new java.awt.Font("Tw Cen MT", 1, 34)); // NOI18N
        menuTextLabel.setForeground(new java.awt.Color(255, 255, 204));
        menuTextLabel.setText("MAIN MENU");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 10, 0);
        mainMenu.add(menuTextLabel, gridBagConstraints);

        learningButton.setBackground(java.awt.SystemColor.control);
        learningButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        learningButton.setForeground(new java.awt.Color(51, 0, 51));
        learningButton.setText("Learning Aboout Deepfake");
        learningButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        learningButton.setPreferredSize(new java.awt.Dimension(200, 35));
        learningButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                learningButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        mainMenu.add(learningButton, gridBagConstraints);

        quizButton.setBackground(java.awt.SystemColor.control);
        quizButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        quizButton.setForeground(new java.awt.Color(51, 0, 51));
        quizButton.setText("Take a Quiz");
        quizButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        quizButton.setPreferredSize(new java.awt.Dimension(200, 35));
        quizButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quizButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        mainMenu.add(quizButton, gridBagConstraints);

        badgeButton.setBackground(java.awt.SystemColor.control);
        badgeButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        badgeButton.setForeground(new java.awt.Color(51, 0, 51));
        badgeButton.setText("Badge Collection");
        badgeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        badgeButton.setPreferredSize(new java.awt.Dimension(200, 35));
        badgeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                badgeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        mainMenu.add(badgeButton, gridBagConstraints);

        leaderboardButton.setBackground(java.awt.SystemColor.control);
        leaderboardButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        leaderboardButton.setForeground(new java.awt.Color(51, 0, 51));
        leaderboardButton.setText("LeaderBoard");
        leaderboardButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        leaderboardButton.setPreferredSize(new java.awt.Dimension(200, 35));
        leaderboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        mainMenu.add(leaderboardButton, gridBagConstraints);

        exitButton.setBackground(java.awt.SystemColor.control);
        exitButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(51, 0, 51));
        exitButton.setText("Exit");
        exitButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exitButton.setPreferredSize(new java.awt.Dimension(200, 35));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.insets = new java.awt.Insets(25, 0, 0, 0);
        mainMenu.add(exitButton, gridBagConstraints);

        switchAccBtn.setBackground(new java.awt.Color(51, 0, 51));
        switchAccBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        switchAccBtn.setForeground(new java.awt.Color(255, 255, 204));
        switchAccBtn.setText("Switch account");
        switchAccBtn.setBorder(null);
        switchAccBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                switchAccBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        mainMenu.add(switchAccBtn, gridBagConstraints);

        userLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(255, 255, 204));
        userLabel.setText("Welcome, Yeop");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        mainMenu.add(userLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        add(mainMenu, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void badgeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_badgeButtonActionPerformed
        // Initiliase BadgePanel after login
        BadgePanel badgePanel = new BadgePanel();
        badgePanel.setMainPanel(mainPanel);
        mainPanel.add(badgePanel, "badge");
        // Switch to BadgePanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "badge");
    }//GEN-LAST:event_badgeButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);  // exits the app
    }//GEN-LAST:event_exitButtonActionPerformed

    private void learningButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_learningButtonActionPerformed
        // Switch to LearningPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "learning");
    }//GEN-LAST:event_learningButtonActionPerformed

    private void quizButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quizButtonActionPerformed
       // Switch to QuizPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "quiz");
    }//GEN-LAST:event_quizButtonActionPerformed

    private void leaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonActionPerformed
        // Initiliase LeaderboardPanel after login
        LeaderboardPanel lbPanel = new LeaderboardPanel(); // default display of leaderboard
        lbPanel.setMainPanel(mainPanel);
        mainPanel.add(lbPanel, "leaderboard");
        lbPanel.refresh("1");
        // Switch to LeaderboardPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "leaderboard");
    }//GEN-LAST:event_leaderboardButtonActionPerformed

    private void switchAccBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_switchAccBtnActionPerformed
        // Switch to SignUpPanel
        CardLayout card = (CardLayout)(mainPanel.getLayout());
        card.show(mainPanel,"welcome");
    }//GEN-LAST:event_switchAccBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badgeButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton leaderboardButton;
    private javax.swing.JButton learningButton;
    private javax.swing.JPanel mainMenu;
    private javax.swing.JLabel menuTextLabel;
    private javax.swing.JButton quizButton;
    private javax.swing.JButton switchAccBtn;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}

