/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import javax.swing.*;
import java.awt.*;

// Creator: HII SIEW CHIENG (97444)
// Tester: CHAN CHIN XUAN (98439)

// Quiz Selection Panel
public class QuizPanel extends javax.swing.JPanel {

    private JPanel mainPanel;
    private FillBlanksPanel fbPanel;
    private MCQPanel mcqPanel;
    private TrueFalsePanel tfPanel;
    private MatchingPanel mcPanel;
    private String currentTopic;
    
    // Constructor
    public QuizPanel() {
        
        initComponents();
    }
    
    public String getCurrentTopic() {
        return currentTopic;
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
    
    public void setFillBlanksPanel(FillBlanksPanel fbPanel) {
        this.fbPanel = fbPanel;
    }
    
    public void setTrueFalsePanel(TrueFalsePanel tfPanel) {
        this.tfPanel = tfPanel;
    }
    
    public void setMatchingPanel(MatchingPanel mcPanel) {
        this.mcPanel = mcPanel;
    }
    
    public void setMCQPanel(MCQPanel mcqPanel) {
        this.mcqPanel = mcqPanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        quizLabel = new javax.swing.JLabel();
        backMenuButton = new javax.swing.JButton();
        topic1_quizBtn = new javax.swing.JButton();
        topic2_quizBtn = new javax.swing.JButton();
        topic3_quizBtn = new javax.swing.JButton();
        topic4_quizBtn = new javax.swing.JButton();
        viewHistory = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 51));
        setForeground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(430, 670));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        quizLabel.setFont(new java.awt.Font("DialogInput", 1, 26)); // NOI18N
        quizLabel.setForeground(new java.awt.Color(255, 255, 204));
        quizLabel.setText("Challenge yourself!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 50);
        add(quizLabel, gridBagConstraints);

        backMenuButton.setBackground(new java.awt.Color(51, 0, 51));
        backMenuButton.setFont(new java.awt.Font("STHupo", 1, 24)); // NOI18N
        backMenuButton.setForeground(new java.awt.Color(255, 255, 204));
        backMenuButton.setText("<");
        backMenuButton.setBorder(null);
        backMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backMenuButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 15, 0, 50);
        add(backMenuButton, gridBagConstraints);

        topic1_quizBtn.setBackground(new java.awt.Color(51, 0, 51));
        topic1_quizBtn.setForeground(new java.awt.Color(255, 255, 255));
        topic1_quizBtn.setText("Quiz 1  What is Deepfake?");
        topic1_quizBtn.setActionCommand("");
        topic1_quizBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        topic1_quizBtn.setPreferredSize(new java.awt.Dimension(300, 40));
        topic1_quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic1_quizBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.insets = new java.awt.Insets(60, 16, 50, 0);
        add(topic1_quizBtn, gridBagConstraints);

        topic2_quizBtn.setBackground(new java.awt.Color(51, 0, 51));
        topic2_quizBtn.setForeground(new java.awt.Color(255, 255, 255));
        topic2_quizBtn.setText("Quiz 2  Do you know what is real and fake?");
        topic2_quizBtn.setActionCommand("");
        topic2_quizBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        topic2_quizBtn.setPreferredSize(new java.awt.Dimension(300, 40));
        topic2_quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic2_quizBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 50, 0);
        add(topic2_quizBtn, gridBagConstraints);

        topic3_quizBtn.setBackground(new java.awt.Color(51, 0, 51));
        topic3_quizBtn.setForeground(new java.awt.Color(255, 255, 255));
        topic3_quizBtn.setText("Quiz 3  Risk of Deepfake!");
        topic3_quizBtn.setActionCommand("");
        topic3_quizBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        topic3_quizBtn.setPreferredSize(new java.awt.Dimension(300, 40));
        topic3_quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic3_quizBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 50, 0);
        add(topic3_quizBtn, gridBagConstraints);

        topic4_quizBtn.setBackground(new java.awt.Color(51, 0, 51));
        topic4_quizBtn.setForeground(new java.awt.Color(255, 255, 255));
        topic4_quizBtn.setText("Quiz 4  Solution and Prevention");
        topic4_quizBtn.setActionCommand("");
        topic4_quizBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        topic4_quizBtn.setPreferredSize(new java.awt.Dimension(300, 40));
        topic4_quizBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topic4_quizBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 0, 0);
        add(topic4_quizBtn, gridBagConstraints);

        viewHistory.setBackground(new java.awt.Color(51, 0, 51));
        viewHistory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewHistory.setForeground(new java.awt.Color(255, 255, 204));
        viewHistory.setText("My History Attempts");
        viewHistory.setBorder(null);
        viewHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewHistoryActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(35, 16, 40, 0);
        add(viewHistory, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void backMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backMenuButtonActionPerformed
        // Switch to MenuPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "menu");
    }//GEN-LAST:event_backMenuButtonActionPerformed

    private void topic2_quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic2_quizBtnActionPerformed
        // Switch to QuestionPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "tf");
        currentTopic = "2";
        tfPanel.startTimer();
    }//GEN-LAST:event_topic2_quizBtnActionPerformed

    private void topic1_quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic1_quizBtnActionPerformed
        // Switch to QuestionPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "fb");
        currentTopic = "1";
        fbPanel.startTimer();
    }//GEN-LAST:event_topic1_quizBtnActionPerformed

    private void topic3_quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic3_quizBtnActionPerformed
        // Switch to QuestionPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "mc");
        currentTopic = "3";
        mcPanel.startTimer();
    }//GEN-LAST:event_topic3_quizBtnActionPerformed

    private void topic4_quizBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topic4_quizBtnActionPerformed
        // Switch to QuestionPanel
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, "mcq");
        currentTopic = "4";
        System.out.println("Quiz Panel, Quiz start!");
        mcqPanel.startTimer();
    }//GEN-LAST:event_topic4_quizBtnActionPerformed

    private void viewHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewHistoryActionPerformed
        // Switch to QuizHistoryPanel
        QuizHistoryPanel historyPanel = new QuizHistoryPanel();
        historyPanel.setMainPanel(mainPanel);
        mainPanel.add(historyPanel, "history");
        CardLayout card = (CardLayout)(mainPanel.getLayout());
        card.show(mainPanel,"history");
    }//GEN-LAST:event_viewHistoryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backMenuButton;
    private javax.swing.JLabel quizLabel;
    private javax.swing.JButton topic1_quizBtn;
    private javax.swing.JButton topic2_quizBtn;
    private javax.swing.JButton topic3_quizBtn;
    private javax.swing.JButton topic4_quizBtn;
    private javax.swing.JButton viewHistory;
    // End of variables declaration//GEN-END:variables
}
