/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontend;
import backend.UserData;
import backend.UserDataException;
import java.awt.*;
import javax.swing.*;

// Creator: TIONG WOEI CHIN (101224)
// Tester: CHIN PEI YI (98485)

// Sign Up Panel
public class SignUpPanel extends javax.swing.JPanel {

    private final char defaultEcho;
    private JPanel mainPanel;
    
    // Constructor
    public SignUpPanel() {
        initComponents();
        defaultEcho = passwordField.getEchoChar();
    }
    
    public void setMainPanel(JPanel mainPanel) {
        this.mainPanel = mainPanel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        passwordField = new javax.swing.JPasswordField();
        signUpLabel = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        startButton = new javax.swing.JButton();
        loginPageBtn = new javax.swing.JButton();
        eyeButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 0, 51));
        setPreferredSize(new java.awt.Dimension(430, 670));
        setLayout(new java.awt.GridBagLayout());

        passwordField.setBackground(new java.awt.Color(51, 0, 51));
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        passwordField.setMinimumSize(null);
        passwordField.setOpaque(true);
        passwordField.setPreferredSize(new java.awt.Dimension(220, 50));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(8, 30, 3, 0);
        add(passwordField, gridBagConstraints);

        signUpLabel.setFont(new java.awt.Font("Yu Gothic Medium", 0, 34)); // NOI18N
        signUpLabel.setForeground(new java.awt.Color(255, 255, 204));
        signUpLabel.setText("Sign Up");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(33, 30, 33, 0);
        add(signUpLabel, gridBagConstraints);

        usernameField.setBackground(new java.awt.Color(51, 0, 51));
        usernameField.setForeground(new java.awt.Color(255, 255, 255));
        usernameField.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Enter username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        usernameField.setMinimumSize(new java.awt.Dimension(0, 0));
        usernameField.setOpaque(true);
        usernameField.setPreferredSize(new java.awt.Dimension(220, 50));
        usernameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 18, 0);
        add(usernameField, gridBagConstraints);

        startButton.setBackground(new java.awt.Color(255, 255, 204));
        startButton.setFont(new java.awt.Font("SimSun-ExtB", 1, 14)); // NOI18N
        startButton.setForeground(new java.awt.Color(51, 0, 51));
        startButton.setText("Start");
        startButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        startButton.setMinimumSize(new java.awt.Dimension(0, 0));
        startButton.setPreferredSize(new java.awt.Dimension(100, 35));
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.insets = new java.awt.Insets(35, 30, 0, 0);
        add(startButton, gridBagConstraints);

        loginPageBtn.setBackground(new java.awt.Color(51, 0, 51));
        loginPageBtn.setForeground(new java.awt.Color(255, 255, 255));
        loginPageBtn.setText("Already have an account? Login");
        loginPageBtn.setBorder(null);
        loginPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginPageBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.insets = new java.awt.Insets(11, 30, 0, 0);
        add(loginPageBtn, gridBagConstraints);

        eyeButton.setBackground(new java.awt.Color(51, 0, 51));
        eyeButton.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        eyeButton.setForeground(new java.awt.Color(255, 255, 255));
        eyeButton.setText("👁");
        eyeButton.setBorder(null);
        eyeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        eyeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(13, 11, 0, 0);
        add(eyeButton, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void usernameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // Store username and password in csv file
        String inputUsername;
        String inputPassword;

        // get input string
        inputUsername = usernameField.getText();
        inputPassword = new String(passwordField.getPassword());
        
        
        // Validate empty input
        if (inputUsername.isEmpty() || inputPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty.","Input error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Verify credentials
            if (UserData.validateCredentials(inputUsername, inputPassword)) {
                // if account exists
                JOptionPane.showMessageDialog(this, "This account already existed. Please try again or login.", "Error", JOptionPane.ERROR_MESSAGE);

            } else { // sign up for new user
                // Save to dataset
                UserData.saveCredentials(inputUsername, inputPassword);

                // Save to UserData class for later use
                UserData.setUsername(inputUsername);
                UserData.setPassword(inputPassword);

                // Show welcome message if account existed
                JOptionPane.showMessageDialog(this, "Welcome aboard, " + inputUsername + "!");

                MenuPanel menuPanel = new MenuPanel();
                menuPanel.setMainPanel(mainPanel);  
                mainPanel.add(menuPanel, "menu");   
                // Switch to MenuPanel
                CardLayout card = (CardLayout)(mainPanel.getLayout());
                card.show(mainPanel,"menu");
            }
        } catch (UserDataException e) {
            JOptionPane.showMessageDialog(this, 
                "An error occurred for signing up:\n" + e.getMessage(),
                "Sign Up Error", 
                JOptionPane.ERROR_MESSAGE);
        }
        
        usernameField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_startButtonActionPerformed

    private void loginPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginPageBtnActionPerformed
        usernameField.setText("");
        passwordField.setText("");
        // Switch to LoginPanel
        CardLayout card = (CardLayout)(mainPanel.getLayout());
        card.show(mainPanel,"login");
    }//GEN-LAST:event_loginPageBtnActionPerformed

    private void eyeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeButtonActionPerformed
        eyeButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        if (passwordField.getEchoChar() == 0) {
            passwordField.setEchoChar(defaultEcho); // Restore original mask
        } else {
            passwordField.setEchoChar((char) 0); // Show password
        }
    }//GEN-LAST:event_eyeButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton eyeButton;
    private javax.swing.JButton loginPageBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel signUpLabel;
    private javax.swing.JButton startButton;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
